### ISSUE TITLE
Error when running examples/prince_ti 

### ISSUE THREAD

**Issue by KarthikGanesan88** [IAIK/coco-alma#7]
Hi! Thank you for sharing this great work! I have been trying to run through the examples but I am getting an error when I try to run `examples/prince_ti`. The error occurs during the `verify` step. 

```
python3 /home/karthik/projects/coco-alma/verify.py 
    --top-module top_module_d11
    --json /home/karthik/projects/coco-alma/tmp/circuit.json 
    --vcd /home/karthik/projects/coco-alma/tmp/tmp.vcd
    --label /home/karthik/projects/coco-alma/examples/prince_ti/labels.txt 
    --rst-name i_reset 
    --cycles 3 
    --mode transient 
    --probing-model time-constrained 
    --num-leaks 1

| CircuitGraph | Total: 6915 | Linear: 3146 | Non-linear: 1065 | Registers:  905 | Mux: 1211 | 
/home/karthik/projects/coco-alma/tmp/tmp.vcd:10574: [WARNING] Entry for name i_clk already exists in namemap (i_clk -> dW)
/home/karthik/projects/coco-alma/tmp/tmp.vcd:10575: [WARNING] Entry for name i_enc_dec already exists in namemap (i_enc_dec -> eW)
/home/karthik/projects/coco-alma/tmp/tmp.vcd:10576: [WARNING] Entry for name i_key1 already exists in namemap (i_key1 -> fW)
/home/karthik/projects/coco-alma/tmp/tmp.vcd:10577: [WARNING] Entry for name i_key2 already exists in namemap (i_key2 -> jW)
/home/karthik/projects/coco-alma/tmp/tmp.vcd:10578: [WARNING] Entry for name i_load already exists in namemap (i_load -> nW)
/home/karthik/projects/coco-alma/tmp/tmp.vcd:10579: [WARNING] Entry for name i_pt1 already exists in namemap (i_pt1 -> oW)
/home/karthik/projects/coco-alma/tmp/tmp.vcd:10580: [WARNING] Entry for name i_pt2 already exists in namemap (i_pt2 -> qW)
/home/karthik/projects/coco-alma/tmp/tmp.vcd:10581: [WARNING] Entry for name i_r already exists in namemap (i_r -> sW)
/home/karthik/projects/coco-alma/tmp/tmp.vcd:10582: [WARNING] Entry for name i_reset already exists in namemap (i_reset -> uW)
/home/karthik/projects/coco-alma/tmp/tmp.vcd:10583: [WARNING] Entry for name i_start already exists in namemap (i_start -> vW)
Traceback (most recent call last):
  File "/home/karthik/projects/coco-alma/verify.py", line 223, in <module>
    main()
  File "/home/karthik/projects/coco-alma/verify.py", line 195, in main
    trace = VCDStorage(args.vcd_file_path)
  File "/home/karthik/projects/coco-alma/VCDStorage.py", line 28, in __init__
    self.parse_header()
  File "/home/karthik/projects/coco-alma/VCDStorage.py", line 75, in parse_header
    assert (up - down + 1 == signal_width), "%s:%d Signal width does not match" % (self.vcd_file_path, self.line_nr)
AssertionError: /home/karthik/projects/coco-alma/tmp/tmp.vcd:10611 Signal width does not match
```
Line 10611 in `tmp.vcd` is `$var wire  4 $' inaff.SHARE1[0].sh1.i_in1 [0:3] $end`. Its hard to tell from this what the signals are. 

I tried running the various steps manually as well as with `run_pipeline.py` but I see the same issue.

**Comment by vedadux** [comment]
Commit 858f8554 resolves this issue, among others.
